{% set name = "sacremoses" %}
{% set version = "0.0.49" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2ecd3a50d1c09a26253ad84b0b89e9e3a28a023455b72a2197cfeab27ff5141

build:
  noarch: python
  number: 0
  entry_points:
    - sacremoses=sacremoses.cli:cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - joblib
    - python >=3.6
    - regex
    - six
    - tqdm

test:
  imports:
    - sacremoses
  commands:
    - sacremoses --help

about:
  home: https://github.com/alvations/sacremoses
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: SacreMoses

extra:
  recipe-maintainers:
    - roccqqck
