{% set name = "sacremoses" %}
{% set version = "0.0.53" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43715868766c643b35de4b8046cce236bfe59a7fa88b25eaf6ddf02bacf53a7a

build:
  noarch: python
  number: 0
  entry_points:
    - sacremoses=sacremoses.cli:cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - joblib
    - python >=3.6
    - regex
    - six
    - tqdm

test:
  imports:
    - sacremoses
  commands:
    - sacremoses --help

about:
  home: https://github.com/alvations/sacremoses
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: SacreMoses

extra:
  recipe-maintainers:
    - roccqqck
